// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pxm5Kihzg35qf4Q5Vh_2p9NQHbqPYaA',
    appId: '1:841627091156:web:544af9649b162ba47a7b41',
    messagingSenderId: '841627091156',
    projectId: 'task-manager-app-a59bf',
    authDomain: 'task-manager-app-a59bf.firebaseapp.com',
    storageBucket: 'task-manager-app-a59bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkx2vmSrfkAU-Mu3nT6XVb-mJyPtSo4Vw',
    appId: '1:841627091156:android:2596dd219ec7e0c67a7b41',
    messagingSenderId: '841627091156',
    projectId: 'task-manager-app-a59bf',
    storageBucket: 'task-manager-app-a59bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAl40PkhctYnxJIpgIHmAJIs4OxCRcr4',
    appId: '1:841627091156:ios:4ebad480e40675727a7b41',
    messagingSenderId: '841627091156',
    projectId: 'task-manager-app-a59bf',
    storageBucket: 'task-manager-app-a59bf.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAl40PkhctYnxJIpgIHmAJIs4OxCRcr4',
    appId: '1:841627091156:ios:4ebad480e40675727a7b41',
    messagingSenderId: '841627091156',
    projectId: 'task-manager-app-a59bf',
    storageBucket: 'task-manager-app-a59bf.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0pxm5Kihzg35qf4Q5Vh_2p9NQHbqPYaA',
    appId: '1:841627091156:web:2eb81b35283671ec7a7b41',
    messagingSenderId: '841627091156',
    projectId: 'task-manager-app-a59bf',
    authDomain: 'task-manager-app-a59bf.firebaseapp.com',
    storageBucket: 'task-manager-app-a59bf.appspot.com',
  );
}
