// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP8Ed06jGnto6WK-Cn4vwOnvyLkLGsqwQ',
    appId: '1:1058652756280:web:7b5f54c77f9623367e89cd',
    messagingSenderId: '1058652756280',
    projectId: 'task-manager-app-d5f1f',
    authDomain: 'task-manager-app-d5f1f.firebaseapp.com',
    storageBucket: 'task-manager-app-d5f1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpIOWKPqDFcL_hsDA6XY-4BEuNrbBeZAE',
    appId: '1:1058652756280:android:2449758a544a607e7e89cd',
    messagingSenderId: '1058652756280',
    projectId: 'task-manager-app-d5f1f',
    storageBucket: 'task-manager-app-d5f1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNK4vqYRbDjPPR1Jqk8oFqcm6KuzxptA',
    appId: '1:1058652756280:ios:a9d4afcc188fffe97e89cd',
    messagingSenderId: '1058652756280',
    projectId: 'task-manager-app-d5f1f',
    storageBucket: 'task-manager-app-d5f1f.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKNK4vqYRbDjPPR1Jqk8oFqcm6KuzxptA',
    appId: '1:1058652756280:ios:a9d4afcc188fffe97e89cd',
    messagingSenderId: '1058652756280',
    projectId: 'task-manager-app-d5f1f',
    storageBucket: 'task-manager-app-d5f1f.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP8Ed06jGnto6WK-Cn4vwOnvyLkLGsqwQ',
    appId: '1:1058652756280:web:b2ec8d99faf1b2ca7e89cd',
    messagingSenderId: '1058652756280',
    projectId: 'task-manager-app-d5f1f',
    authDomain: 'task-manager-app-d5f1f.firebaseapp.com',
    storageBucket: 'task-manager-app-d5f1f.appspot.com',
  );
}
